---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install ruby
      apt:  name=ruby
    - name: install postgresql
      apt:  name=postgresql
    - include: tasks/apache.yml
    - include: tasks/mysql.yml
    - include: tasks/php.yml

