---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - include: tasks/apache.yml
    - include: tasks/postgres.yml
    - include: tasks/ruby.yml
    - include: tasks/mysql.yml
    - include: tasks/php.yml

